name: Build image

on:
  push:
    branches: [ '*' ]

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
    - name: Determine branch name
      id: version
      run: |
        branch=${REF#refs\/heads\/}
        [[ $branch != "master" ]] || branch=latest
        printf "branch=%s\n" "$branch" >> $GITHUB_OUTPUT
      env:
        REF: ${{ github.ref }}
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to docker hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN_RW }}
    - name: Build & push
      uses: docker/build-push-action@v4
      with:
        file: Dockerfile
        tags: secoya/smallstep-wrapper:${{ steps.version.outputs.branch }}
        push: true
