name: Release

on:
  push:
    tags: [ 'v*' ]

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
    - name: Determine version
      id: version
      run: printf "tag=%s\n" "${REF#refs\/tags\/v}" >> $GITHUB_OUTPUT
      env:
        REF: ${{ github.ref }}
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: v${{ steps.version.outputs.tag }}
    - name: Set up buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to docker hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN_RW }}
    - name: Build & push
      uses: docker/build-push-action@v4
      with:
        file: Dockerfile
        tags: secoya/smallstep-wrapper:${{ steps.version.outputs.tag }}
        push: true
