name: Release

on:
  push:
    branches: [ '*' ]
    tags: [ 'v*' ]

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
    - id: version
      uses: orbit-online/image-version@v0.9.1
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to docker hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN_RW }}
    - name: Build & push
      uses: docker/build-push-action@v4
      with:
        file: Dockerfile
        tags: secoya/smallstep-wrapper:${{ steps.version.outputs.version }}
        push: true
        build-args: |
          "BUILD_TOOL=github"
          "BUILT_BY=${{ github.actor }}"
